export type { default as ExtensionFactory } from "./src/api/plugin/ExtensionFactory.ts";
export type { default as ExtensionDescriptor } from "./src/api/plugin/ExtensionDescriptor.ts";
export type { default as Plugin } from "./src/api/plugin/Plugin.ts";
export type { default as PluginDependency } from "./src/api/plugin/PluginDependency.ts";
export type { default as VersionedPlugin } from "./src/api/plugin/VersionedPlugin.ts";
export type { default as ExtensionInfo } from "./src/api/plugin_manager/ExtensionInfo.ts";
export type { default as PluginManager } from "./src/api/plugin_manager/PluginManager.ts";
export type { default as PluginRepository } from "./src/api/plugin_repository/PluginRepository.ts";
export type { default as PluginDescriptor } from "./src/api/plugin_repository/PluginDescriptor.ts";
export type { default as ExtensionEntry } from "./src/api/plugin_repository/ExtensionEntry.ts";
export type { default as VersionedPluginDescriptor } from "./src/api/plugin_repository/VersionedPluginDescriptor.ts";
export type { default as SearchQuery } from "./src/api/plugin_repository/SearchQuery.ts";
export type { default as VersionedPluginRepository } from "./src/api/plugin_repository/VersionedPluginRepository.ts";
export type { default as MarketplacePluginRepository } from "./src/api/plugin_repository/MarketplacePluginRepository.ts";
export type { default as ExtensionRegistry } from "./src/api/registry/ExtensionRegistry.ts";
export type { default as ExtensionPointRegistry } from "./src/api/registry/ExtensionPointRegistry.ts";
export type { default as PluginInstaller } from "./src/api/plugin_installer/PluginInstaller.ts";
export type { default as SpawnInterface, SpawnResult } from "./src/api/spawn/SpawnInterface.ts";
export type { default as SpawnCapable } from "./src/api/spawn/SpawnCapable.ts";
export type { default as FetchInterface } from "./src/api/fetch/FetchInterface.ts";
export type { default as FetchCapable } from "./src/api/fetch/FetchCapable.ts";
export { default as DefaultPluginManager } from "./src/plugin_manager/DefaultPluginManager.ts";
export { default as UrlListPluginRepository } from "./src/plugin_manager/plugin_repository/UrlListPluginRepository.ts";
export { default as LocalFolderPluginRepository } from "./src/plugin_manager/plugin_repository/LocalFolderPluginRepository.ts";
export { default as HttpManifestPluginRepository } from "./src/plugin_manager/plugin_repository/HttpManifestPluginRepository.ts";
export { default as NpmPluginRepository } from "./src/plugin_manager/plugin_repository/NpmPluginRepository.ts";
export { default as NpmjsPluginRepository } from "./src/plugin_manager/plugin_repository/NpmjsPluginRepository.ts";
export type { NpmSearchQuery } from "./src/plugin_manager/plugin_repository/NpmjsPluginRepository.ts";
export type { default as MarketplacePluginManager } from "./src/api/plugin_manager/MarketplacePluginManager.ts";
export { default as BaseMarketplacePluginManager } from "./src/plugin_manager/BaseMarketplacePluginManager.ts";
export { default as NpmPluginManager } from "./src/plugin_manager/NpmPluginManager.ts";
export { default as HttpPluginManager } from "./src/plugin_manager/HttpPluginManager.ts";
